services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-a-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: service-a-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: service-a-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: auction_catalog
      MYSQL_USER: auction
      MYSQL_PASSWORD: auction
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: service-a-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
